name: Atualizar API
on:
  push:
    branches:
      - main
jobs:
  update-api:
    name: Atualizar API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout da API
        uses: actions/checkout@v2
        with:
          repository: BABorges/api-ByteBank
          ref: main
          path: api-ByteBank
      - name: Instalar dependências e iniciar API
        working-directory: api-ByteBank
        run: |
          npm install
          npm run start-api
