name: Pepeline de testes usando o Cypress//

on:
  push:
    branches:
      - main

jobs:
  update-api:
    name: Atualizar API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout da API
        uses: actions/checkout@v2
        with:
          repository: BABorges/api-ByteBank
          ref: main
          path: api-ByteBank
      - name: Instalar dependências e iniciar API
        working-directory: api-ByteBank
        run: |
          npm install
          npm run start-api

  update-front:
    name: Atualizar Front
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Front
        uses: actions/checkout@v2
        with:
          repository: BABorges/ByteBank
          ref: main
          path: ByteBank
      - name: Instalar dependências e iniciar Front
        working-directory: ByteBank
        run: |
          npm install
          npm run start-front

  test:
            name: Executar os testes Cypress
            runs-on: ubuntu-latest
            steps:
              - name: Esperar 60 segundos antes de começar
                run: sleep 60s
              - name: Checkout do código
                uses: actions/checkout@v2
              - name: Executar os testes Cypress
                run: |
                  npm install
                  npx cypress run --headless 