name: Pepeline de testes usando o Cypress//

on:
  push:
    branches:
      - main

jobs:
  update-api:
    name: Atualizar API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout da API
        uses: actions/checkout@v2
        with:
          repository: BABorges/api-ByteBank
          ref: main
          path: api-ByteBank
      - name: Instalar dependências e iniciar API
        working-directory: api-ByteBank
        run: |
          npm install
          npm run start-api

  update-front:
    name: Atualizar Front
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Front
        uses: actions/checkout@v2
        with:
          repository: BABorges/ByteBank
          ref: main
          path: ByteBank
      - name: Instalar dependências e iniciar Front
        working-directory: ByteBank
        run: |
          npm install
          npm run start-front

  wait-20-seconds:
            name: Aguardar 20 segundos
            runs-on: ubuntu-latest
            steps:
              - name: Esperar 20 segundos
                run: sleep 20s
  test:
            name: Executar os testes Cypress
            runs-on: ubuntu-latest
            needs: wait-20-seconds
            steps:
              - name: Esperar 20 segundos antes de começar
                run: sleep 20s
              - name: Checkout do código
                uses: actions/checkout@v2
              - name: Executar os testes Cypress
                run: |
                  npm install cypress
                  npx cypress run