name: Pepeline de testes usando o Cypress
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Pepiline de testes usando o Cypress
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git credentials
        run: |
          git config --global credential.helper store
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git config --global --unset-all credential.helper
          echo "machine github.com login BABorges password apiByteBankToken" > ~/.netrc
      - name: Checkout do código
        uses: actions/checkout@v4
      - name: Configurar o Node JS
        uses: actions/setup-node@v4
        with:
          node-version: 14.x 
      - name: Instalar as dependências
        run: npm install
      - name: Inicializar e atualizar submódulos
        run: git submodule update --init --recursive
      - name: Instalar dependências e executar
        run: npm install json-server
             npm run start-api
      - name: Subir o Front
        run: npm start
      - name: Executar os testes Cypress
        run: npx cypress run
