name: Pepeline de testes usando o Cypress

on:
  push:
    branches:
      - main

jobs:
  update:
    name: Atualizar API e Front
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job-type: ['api', 'front']
    steps:
      - name: Checkout do código
        uses: actions/checkout@v2
      - name: Instalar dependências e iniciar
        run: |
          if [ ${{ matrix.job-type }} == 'api' ]; then
            cd api-ByteBank
            npm install
            npm run start-api
          else
            cd ByteBank
            npm install
            npm run start-front
          fi
      - name: Executar os testes Cypress
        run: npx cypress run
